package httpapi_test

import (
	"encoding/base64"
	"encoding/json"
	"strings"
	"testing"
	"time"

	httpapi "github.com/lboyeon1223/gym-check-in/backend/internal/http"
)

// TestCursorRoundTrip verifies an encoded cursor decodes back to the same
// (UTC-normalised) timestamp and id. The shared helper backs both members
// (step 5) and check-ins (step 7) pagination — drift here would split tests
// across handlers and silently change page boundaries.
func TestCursorRoundTrip(t *testing.T) {
	in := httpapi.Cursor{
		T:  time.Date(2026, 4, 27, 18, 23, 45, 123_000_000, time.UTC),
		ID: 12345,
	}
	enc := httpapi.EncodeCursor(in)
	if enc == "" {
		t.Fatalf("encode returned empty string")
	}
	out, err := httpapi.DecodeCursor(enc)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	if !out.T.Equal(in.T) {
		t.Errorf("time drift: got %v want %v", out.T, in.T)
	}
	if out.ID != in.ID {
		t.Errorf("id drift: got %d want %d", out.ID, in.ID)
	}
}

func TestDecodeCursor_RejectsMalformed(t *testing.T) {
	cases := map[string]string{
		"empty":        "",
		"not base64":   "!!!not-base64!!!",
		"not json":     base64.RawURLEncoding.EncodeToString([]byte("not-json")),
		"missing t":    base64.RawURLEncoding.EncodeToString([]byte(`{"id":1}`)),
		"missing id":   base64.RawURLEncoding.EncodeToString([]byte(`{"t":"2026-04-27T00:00:00Z"}`)),
		"bad t":        base64.RawURLEncoding.EncodeToString([]byte(`{"t":"yesterday","id":1}`)),
		"bad id type":  base64.RawURLEncoding.EncodeToString([]byte(`{"t":"2026-04-27T00:00:00Z","id":"abc"}`)),
		"id is float":  base64.RawURLEncoding.EncodeToString([]byte(`{"t":"2026-04-27T00:00:00Z","id":1.5}`)),
		"random bytes": base64.RawURLEncoding.EncodeToString([]byte{0x00, 0x01, 0x02}),
	}
	for name, enc := range cases {
		t.Run(name, func(t *testing.T) {
			if _, err := httpapi.DecodeCursor(enc); err == nil {
				t.Fatalf("expected error for case %q", name)
			}
		})
	}
}

// TestDecodeCursor_AcceptsPaddedBase64 ensures cursors generated by clients
// using stdlib base64.URLEncoding (which adds '=' padding) still decode.
func TestDecodeCursor_AcceptsPaddedBase64(t *testing.T) {
	payload := map[string]any{"t": "2026-04-27T00:00:00Z", "id": 7}
	raw, _ := json.Marshal(payload)
	padded := base64.URLEncoding.EncodeToString(raw)
	if !strings.Contains(padded, "=") {
		// Length happened to align — re-make sure we still get a valid decode.
		_, err := httpapi.DecodeCursor(padded)
		if err != nil {
			t.Fatalf("decode unpadded: %v", err)
		}
		return
	}
	if _, err := httpapi.DecodeCursor(padded); err != nil {
		t.Fatalf("decode padded base64: %v", err)
	}
}

func TestParseLimit(t *testing.T) {
	cases := []struct {
		name    string
		input   string
		def     int
		max     int
		want    int
		wantErr bool
	}{
		{"empty default", "", 20, 100, 20, false},
		{"valid", "5", 20, 100, 5, false},
		{"max boundary", "100", 20, 100, 100, false},
		{"one boundary", "1", 20, 100, 1, false},
		{"zero", "0", 20, 100, 0, true},
		{"negative", "-1", 20, 100, 0, true},
		{"over max", "101", 20, 100, 0, true},
		{"non integer", "abc", 20, 100, 0, true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, err := httpapi.ParseLimit(c.input, c.def, c.max)
			if (err != nil) != c.wantErr {
				t.Fatalf("err mismatch: %v wantErr=%v", err, c.wantErr)
			}
			if !c.wantErr && got != c.want {
				t.Fatalf("got=%d want=%d", got, c.want)
			}
		})
	}
}
